Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "client"
  config.vm.network :private_network, ip: "10.0.1.3"

  config.vm.provision "shell", inline: <<-SHELL
    # Mise à jour des paquets
    sudo apt update
    sudo apt-get install -y curl nmap
  SHELL
end
